name: Build Fork

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  bundle_windows_x86_64:
    runs-on: windows-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Rust
        uses: dtolnay/rust-action@stable

      - name: Build
        run: cargo build --release -p zed
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-x86_64
          path: target/release/zed.exe
          if-no-files-found: error

    timeout-minutes: 120
