name: Build Fork

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  bundle_windows_x86_64:
    runs-on: windows-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: steps::checkout_repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          clean: false

      - name: steps::setup_node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "20"

      - name: run_bundling::bundle_windows::bundle_windows
        run: script/bundle-windows.ps1 -Architecture x86_64
        shell: pwsh

      - name: Upload Zed-x86_64.exe
        uses: actions/upload-artifact@v4
        with:
          name: Zed-x86_64.exe
          path: target/Zed-x86_64.exe
          if-no-files-found: error

    timeout-minutes: 120

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
